export interface jobsData {
    email: String
    companyName: String,
    firstName: String,
    lastName: String,
    address1: String,
    address2: String,
    city: String,
    state: String,
    bathrooms: Number,
    bedrooms: Number,
    postcode: String,
    startHour: String,
    startMin: String,
    startMode: String,
    endHour: String,
    endMin: String,
    subtotal: String,
    endMode: String,
    bookingDate: String,
    subscription: String,
    customerNotes: String,
    service: String,
    notes: Array<[]>,
    phone: String,
    products: Array<[
        {
            "_id": String,
            "title": String,
            "price": Number,
            "quantity": String,
            "createdAt": String,
            "updatedAt": String,
            "__v": Number,
            "icon1": String
        },
    ]>,
    quoteStatus: String,
}